spring:
  application:
    name: monox-usr
  data:
    mongodb:
      uri: mongodb://mk:mk$123@192.168.33.11/monox

server:
  port: 8088
  #Zuul no sabe resolver contexto, por lo que el contexto sera equivalente al application.name
  #contextPath: /monox-usr

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.peer.one:8050/eureka,http://http://eureka.peer.two:8060/eureka
  instance:
    preferIpAddress: true

