spring:
  application:
    name: Zuul Server
server:
  port: 8040

zuul:
  ignoredServices: '*'
  routes:
    MONOX-USR:
      path: /monox-usr/**
      serviceId: MONOX-USR
    MONOX-TKN:
      path: /monox-tkn/**
      serviceId: MONOX-TKN
    MONOX-GEN:
      path: /monox-gen/**
      serviceId: MONOX-GEN
    MONOX-NAT:
      path: /monox-nat/**
      serviceId: MONOX-NAT
    test1:
      path: /hola/**
      serviceId: MONOX-USR
    test2:
      path: /mk/**
      url: http://localhost:8088/test
    test3:
      path: /gal/**
      url: http://localhost:8088/

ribbon:
  eureka:
    enabled: true
    
    
---
spring:
  profiles: sa
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.peer.one:8050/eureka

---
spring:
  profiles: cl
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.peer.one:8050/eureka,http://http://eureka.peer.two:8060/eureka
  